name: Build Arriba dotnetcore

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build Arriba.Core.sln Release
        run: dotnet build ./Arriba/Arriba.Core.sln --configuration Release
      - name: Test Arriba.Core.sln Release
        run: dotnet test Arriba/Arriba.Core.sln --configuration Release -- CollectCoverage=true -- CoverletOutput=TestResults/ -- CoverletOutputFormat=lcov
      - name: Publish Arriba.Core.sln Release to Arriba/bin
        run: dotnet build Arriba/Arriba.Core.sln --configuration Release --output Arriba/bin
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Arriba
          path: Arriba/bin
